package:
   name: fermi-heacore
   version: "0.0.3"

source:
   git_url: https://github.com/Areustle/fermi-heacore.git

build:
  number: 0

requirements:
  build:
    - readline
  run:
    - readline
