package:
   name: fermi-heacore
   version: "0.0.4"

source:
   git_url: https://github.com/Areustle/fermi-heacore.git

build:
  number: 0

requirements:
  build:
    - readline
    - cfitsio
  run:
    - readline
    - cfitsio
